server:
  port: 8081
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bd_usuarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:1234} # Cambia 1234 por tu clave real si prefieres dejarla aqu√≠ de una vez
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: false

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
